#-------------------------------
# General Site Settings

menu:
- {name: 'projects', url: ''}
#- {name: 'blog', url: 'pages/blog.html'}
- {name: 'about', url: 'pages/about.html'}
#- {name: 'contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Colin Ho Personal portfolio'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-27128478-1

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  ## hello there

  I'm a time traveller from the future helping the present catch up
  I design and build tools to help address [existential risks](https://nickbostrom.com/existential/risks.html)

#[resume (09/17)](https://drive.google.com/open?id=1qAU_nWYMN6aBA5UXRQqFFIZ52jyXsG4d)  
#[academic publications](https://scholar.google.com/citations?user=tShE39kAAAAJ&hl=en)  

  

contact: >
  # Contact

  

#-------------------------------
# Work Section

projects:
- {name: 'OpenROV Trident', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Haptic Slip Interface', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'MSLED', folder: 'proj-3', file: 'projects/proj-3.html'}
#- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
#- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/ohcolinho'}
- {icon: 'instagram', link: 'https://www.instagram.com/ohcolinho/'}
- {icon: 'soundcloud', link: 'https://soundcloud.com/algorythms'}
- {icon: 'github', link: 'https://github.com/ohcolinho'}
- {icon: 'facebook', link: 'https://www.facebook.com/ohcolinho'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/hocolin/'}
- {icon: 'envelope', link: 'mailto:colinho42@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
